cerrors/cerrors.go, cerrors/cerrors_test.go
cerrors.New/NewfにLevelを設定する処理を書くのを忘れていた
=> fix: cerrorsにLevelがつかない

.github/dependabot.yml
=> enhancement: dependabot ulid

.github/dependabot.yml, envlookup/envlookup.go, envlookup/envlookup_test.go, envlookup/go.mod, envlookup/go.sum
`os.Getenv` の 薄いwrapperを作成
以下フォーマットに対応
- string
- int
- time.Time
=> feat: add envlookup

aws/awsconfig/awsconfig.go, aws/awss3/awss3.go, aws/awss3/awss3_test.go, aws/awss3/client.go, aws/ctxawslocal/ctxawslocal_test.go, aws/ctxawslocal/options.go
https://github.com/88labs/go-utils/pull/30 での指摘点を修正
loggerに関しては別途検討
=> chore: fix awss3 reviewes

.github/workflows/test-utf8bom.yaml, utf8bom/go.mod, utf8bom/go.sum, utf8bom/utf8bom.go, utf8bom/utf8bom_test.go
UTF8 (BOM) を処理するLibraryを追加
- utf8bom
=> feat: utf8bom

.github/workflows/test-aws.yaml, .gitignore, aws/.gitignore, aws/awss3/awss3.go, aws/awss3/awss3_test.go, aws/awss3/client.go, aws/awss3/options/s3selectcsv/s3_select_csv.go, aws/docker-compose.yaml, aws/docker/minio/policies/policy_test.json, aws/go.mod, aws/go.sum
awss3 に S3 Select でCSVを取得する関数を追加
localstackだとS3 Selectが上手く動作しなかったため、 test module用にMinioを新規に追加
=> feat: awss3 SelectCSV()

aws/awss3/awss3.go, aws/awss3/awss3_test.go, aws/go.mod, aws/go.sum
=> feat: awss3 SelectCSV remove BOM

.github/workflows/test-envlookup.yaml, envlookup/envlookup.go, envlookup/envlookup_test.go, envlookup/go.mod, envlookup/go.sum
- 環境変数からawsconfig.Regionに変換する envlookup.LookUpRegion を追加
- CIを追加
=> feat: envlookup.LookUpRegion

aws/awssqs/awssqs.go, aws/awssqs/awssqs_test.go, aws/awssqs/client.go, aws/awssqs/options/sqsreceive/receive_message_options.go, aws/awssqs/options/sqssend/send_message_options.go, aws/docker-compose.yaml, aws/docker/localstack/init/init.sh, aws/go.mod, aws/go.sum
feat/awssqs
- SentMessage
- ReceiveMessage
- DeleteMessage
=> feat: awssqs

aws/awssqs/awssqs_test.go, aws/awssqs/client.go, aws/ctxawslocal/ctxawslocal_test.go, aws/ctxawslocal/options.go
- fix awssqs local mock endpoint option
=> fix awssqs local mock endpoint option

aws/awss3/awss3.go, aws/awss3/awss3_test.go, aws/awss3/options/s3selectcsv/s3_select_csv.go
awss3.SelectCSVAll
- WithFileHeaderInfo の廃止
- WithCSVInput の追加
=> chore: awss3 SelectCSVAll options WithCSVInput

aws/awss3/awss3.go, aws/awss3/awss3_test.go, aws/awss3/options/s3download/s3_download.go, aws/docker-compose.yaml
Hi! I found it when I was looking at it, perhaps it is a download?
s/donwload/download/
=> Fix a typo

.github/release-drafter.yml, .github/workflows/release-drafter.yaml
Release tag管理のためrelease-drafterを導入
=> enhancement: release-drafter

.github/workflows/release-drafter.yaml
=> enhancement: release-drafter actions/checkout

.github/release-drafter-aws.yml, .github/release-drafter-cerrors.yml, .github/release-drafter-envlookup.yml, .github/release-drafter-errgroup.yml, .github/release-drafter-osext.yml, .github/release-drafter-sql-escape.yml, .github/release-drafter-tspb_cast.yml, .github/release-drafter-ulid.yml, .github/release-drafter-utf8bom.yml, .github/workflows/release-drafter.yaml
release drafter prefix-tag を library毎に変更
=> enhancement: release drafter prefix-tags

envlookup/go.mod, envlookup/go.sum
```
Updating github.com/88labs/go-utils/aws to version 0.5.0...
```
=> enhancement: envlookup go modules update

utf8bom/go.mod, utf8bom/go.sum
```
Updating github.com/bxcodec/faker/v3 to version 3.8.1...
Updating github.com/stretchr/testify to version 1.8.1...
```
=> enhancement: utf8bom go modules update

.github/release-drafter-aws.yml, .github/release-drafter-cerrors.yml, .github/release-drafter-envlookup.yml, .github/release-drafter-errgroup.yml, .github/release-drafter-osext.yml, .github/release-drafter-sql-escape.yml, .github/release-drafter-tspb_cast.yml, .github/release-drafter-ulid.yml, .github/release-drafter-utf8bom.yml
=> enhancement: release drafter paths

envlookup/envlookup.go, envlookup/envlookup_test.go, envlookup/go.sum
=> feat: envlookup add LookUpBool

aws/awss3/awss3.go, aws/awss3/awss3_test.go
=> feat: awss3 add DeleteObject()

.github/dependabot.yml
=> chore: aws add dependabot

.github/workflows/test-aws.yaml, .github/workflows/test-cerrors.yaml, .github/workflows/test-envlookup.yaml, .github/workflows/test-utf8bom.yaml, README.md, Taskfile.yaml, aws/README.md, aws/go.mod, cerrors/go.mod, envlookup/go.mod, errgroup/go.mod, osext/go.mod, sql-escape/go.mod, tspb_cast/go.mod, ulid/go.mod, utf8bom/go.mod, utf8bom/go.sum
=> enhancement: update go1.20

.github/workflows/release-drafter.yaml
change release drafter `publish: true`
https://github.com/release-drafter/release-drafter#action-inputs
=> change auto release

aws/awssqs/awssqs.go, aws/awssqs/awssqs_test.go
SendMessageGob() : SQS SendMessage  use [encoding/gob](https://pkg.go.dev/encoding/gob) And Base64
ReceiveMessageGob() : SQS ReceiveMessage use  [encoding/gob](https://pkg.go.dev/encoding/gob) And Base64
=> feat: SendMessageGob(), ReceiveMessageGob()

aws/awss3/awss3.go, aws/awss3/awss3_test.go
The standard aws s3 functionality is difficult to understand because NotFound when an Object does not exist may or may not appear, so modify the library to reliably check for the existence of Objects and return a fixed Error.
=> feat: awss3 add ErrNotFound error

aws/awss3/awss3.go, aws/awss3/awss3_test.go, aws/awss3/options/s3head/s3_head.go
Add waiter setting to awss3.Header
=> feat: awss3 Head waiter

aws/awss3/client.go, aws/awssqs/client.go, aws/ctxawslocal/ctxawslocal_test.go, aws/ctxawslocal/options.go
=> chore: ctxawslocal add SessionToken

aws/awss3/awss3.go, aws/awss3/awss3_test.go, aws/awss3/options/s3list/s3_head.go, aws/awssqs/awssqs_test.go, aws/docker-compose.yaml, aws/docker/localstack/docker-entrypoint-initaws.d/init.sh, aws/docker/localstack/init/init.sh, aws/docker/sqs_elasticmq/opt/elasticmq.conf
New implementation of `awss3.ListObjects`
allow `Prefix` to be specified in option.
=> feat: awss3 ListObjects

aws/awss3/awss3.go, aws/awss3/awss3_test.go
Modify to allow timeout in awss3.Head
=> fix: awss3 head with timeout

.github/dependabot.yml
=> enhancement: add dependabot grouping

aws/awss3/awss3.go, aws/awss3/awss3_test.go
make DownloadFilesParallel
and without DownloadFiles  parallel
=> feat: s3 download parallel

README.md, Taskfile.yaml, aws/awscognito/awscognito.go, aws/awsdynamo/awsdynamo_test.go, aws/awsdynamo/client.go, aws/awss3/awss3.go, aws/awss3/awss3_test.go, aws/awss3/client.go, aws/awss3/options/global/global_test.go, aws/awss3/options/global/s3dialer/s3dialer.go, aws/awss3/options/s3head/s3_head.go, aws/awss3/options/s3presigned/s3_presigned.go, aws/awss3/options/s3upload/s3_upload.go, aws/awssqs/awssqs.go, aws/awssqs/awssqs_test.go, aws/awssqs/client.go, aws/awssqs/options/sqssend/send_message_options.go, aws/ctxawslocal/ctxawslocal.go, aws/go.mod, aws/go.sum, envlookup/envlookup_test.go, envlookup/go.mod, envlookup/go.sum, tspb_cast/tspb_cast.go
- replace go-faker/faker/v4
- go-oif format import
=> enhancement: replace go-faker/faker/v4

.github/CODEOWNERS, .github/dependabot.yml, .github/workflows/test-aws.yaml, .github/workflows/test-cerrors.yaml, .github/workflows/test-envlookup.yaml, .github/workflows/test-utf8bom.yaml, aws/go.mod, cerrors/go.mod, envlookup/go.mod, errgroup/go.mod, osext/go.mod, sql-escape/go.mod, tspb_cast/go.mod, ulid/go.mod, utf8bom/go.mod
=> enhancement: go 1.21

aws/awss3/client.go, aws/awss3/options/global/global_test.go, aws/awss3/options/global/s3dialer/s3dialer.go
https://github.com/88labs/go-utils/pull/211
=> add global s3dialer

.github/workflows/test-ulid.yaml, ulid/ulid.go, ulid/ulid_test.go
Added Time() and SetTime() functions for ulid
=> ulid: add SetTime(), Time()

.github/auto_assign_configs.yaml, .github/workflows/auto_assign.yaml
=> enhancement: auto-assign

.github/workflows/dependabot-auto-merge.yaml
dependabot-auto-merge
- github.com/aws/aws-sdk-go-v2 patch version
- tj-actions/changed-files minor/patch version
=> enhancement: dependabot-auto-merge

aws/awss3/options/s3download/s3_download.go, aws/awss3/options/s3head/s3_head.go, aws/awss3/options/s3list/s3_head.go, aws/awss3/options/s3presigned/s3_presigned.go
=> document: add s3 options comment

.github/workflows/secretlint.yml, .github/workflows/semgrep.yml
tj-actions/changed-files が削除されたため、changed-files を 88labs 以下に push しました。
臨時リリースなどで困らないよう、一旦こちらでしのぎます。
=> Replace tj-actions with 88labs for changed-files

.github/workflows/secretlint.yml, .github/workflows/semgrep.yml
- https://github.com/tj-actions/changed-files/issues/2463#issuecomment-2727015784
=> tj-actions/changed-files issue has been solved.

.github/workflows/test-aws.yaml, .github/workflows/test-cerrors.yaml, .github/workflows/test-envlookup.yaml, .github/workflows/test-hashutil.yaml, .github/workflows/test-ulid.yaml, .github/workflows/test-utf8bom.yaml, cerrors/go.mod, envlookup/go.mod, envlookup/go.sum, errgroup/go.mod, hashutil/go.mod, osext/go.mod, ulid/go.mod, utf8bom/go.mod
Unify the supported versions of the library to Go 1.24.x.
Update go modules.
=> enhancement: update Go 1.24

aws/awss3/awss3.go, aws/awss3/awss3_test.go
implement CreateMultipartUpload, UploadPart, CompleteMultipartUpload, AbortMultipartUpload for awss3 package
Org project (and other projects) need to use CreateMultipartUpload function to upload part by part for large file situtation
=> feat: implement CreateMultipartUpload, UploadPart, CompleteMultipartUpload, AbortMultipartUpload for  awss3 package
